/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nguyenhuudai.pkg2080601408;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.CipherInputStream;
import javax.crypto.CipherOutputStream;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESKeySpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class FormEncrypt extends javax.swing.JFrame {

    /**
     * Creates new form FormEncrypt
     */
    int vig[][];
    public FormEncrypt() {
        initComponents();
        vig = new int[26][26];
        for(int i=0;i<26;i++)
            for(int j=0;j<26;j++)
                vig[i][j] = (i+j)%26;
    }
    
    
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtvanban = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKhoa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmahoa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtvanban2 = new javax.swing.JTextField();
        txtNoiChuoi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBam = new javax.swing.JTextField();
        txtvanban3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNoiChuoi2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtKhoa2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtmahoa2 = new javax.swing.JTextField();
        btnMaHoa = new javax.swing.JButton();
        btnNoiChuoi = new javax.swing.JButton();
        btnBamChuoi = new javax.swing.JButton();
        btnNoiChuoi2 = new javax.swing.JButton();
        btnMaHoa2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Form Encrypt");

        jLabel2.setText("Message(M1):");

        jLabel3.setText("Key Ecrypt(K1):");

        jLabel4.setText("Cipher(E1) = En(M1) + K1 :");

        jLabel5.setText("Message(M2):");

        jLabel6.setText("Message(N1) = E1 + M2 :");

        jLabel7.setText("Message Hash (H2):");

        jLabel8.setText("Message(M3):");

        jLabel9.setText("Message(N2) = N1 + H2 + M3 :");

        jLabel10.setText("Key Encrypt(K3):");

        jLabel11.setText("Cipher(E3) = En (N2) + K3  :");

        btnMaHoa.setText("Mã hóa M1");
        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaActionPerformed(evt);
            }
        });

        btnNoiChuoi.setText("Nối chuỗi N1");
        btnNoiChuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoiChuoiActionPerformed(evt);
            }
        });

        btnBamChuoi.setText("Băm chuỗi N1");
        btnBamChuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBamChuoiActionPerformed(evt);
            }
        });

        btnNoiChuoi2.setText("Nỗi chuỗi N2");
        btnNoiChuoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoiChuoi2ActionPerformed(evt);
            }
        });

        btnMaHoa2.setText("Mã hóa N2");
        btnMaHoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoa2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvanban, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvanban2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvanban3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoiChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBam, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoiChuoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmahoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBamChuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMaHoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNoiChuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNoiChuoi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMaHoa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtvanban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmahoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtvanban2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNoiChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNoiChuoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBamChuoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtvanban3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNoiChuoi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNoiChuoi2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtKhoa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtmahoa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaHoa2))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaActionPerformed
        String banro=this.txtvanban.getText();
        String k=this.txtKhoa.getText();
        String banma = mahoa(banro,k);
        this.txtmahoa.setText(banma);             
    }//GEN-LAST:event_btnMaHoaActionPerformed
    
    private String mahoa(String banro,String key){
        int n=banro.length();
        String banma="";
        int k=0;
        for(int i=0; i<n;i++)
            if(Character.isLetter(banro.charAt(i)))
            {
              banma+=mahoa(banro.charAt(i),key.charAt(k));
              k++;
              k=k%key.length();
              
            }else 
                banma+=banro.charAt(i);
        return banma;
    }
    
    char mahoa(char x,char k){
        int xn=Character.toUpperCase(x)-'A';
        int kn=Character.toUpperCase(k)-'A';
        int yn=vig[kn][xn];
        return (char) (yn+'A');
    }
    
    
    private void btnNoiChuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoiChuoiActionPerformed
        // TODO add your handling code here:    
        
        // Lấy giá trị của txtvanban2 và txtmahoa
        String vanban2 = txtvanban2.getText();
        String mahoa = txtmahoa.getText();

        // Nối chuỗi
        String ketqua = mahoa + vanban2;

        // Hiển thị kết quả trên txtNoiChuoi
        txtNoiChuoi.setText(ketqua);
        
        System.out.println("Noi chuoi N1: "+" "+ketqua);
        
         try{
            BufferedWriter bw = null;
            String fileName = "D:\\N1.txt";
            String E1=txtNoiChuoi.getText();
            bw = new BufferedWriter(new FileWriter(fileName));
            bw.write(E1);
            bw.close();
            
            String file = "D:\\E1.txt";
            String E2=txtmahoa.getText();
            bw = new BufferedWriter(new FileWriter(file));
            bw.write(E2);
            bw.close();
            
            String filel = "D:\\M2.txt";
            String E3=txtmahoa.getText();
            bw = new BufferedWriter(new FileWriter(filel));
            bw.write(E3);
            bw.close();
            
            
        }catch(IOException ex)
            {
                
            }
        
        
    }//GEN-LAST:event_btnNoiChuoiActionPerformed

    private void btnBamChuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBamChuoiActionPerformed
        // TODO add your handling code here:
//        
//         try {
//            String chuoi ="";
//            chuoi = txtNoiChuoi.getText();
//            MessageDigest md = MessageDigest.getInstance("SHA-256");
//            md.update(chuoi.getBytes());
//            byte byteData[] = md.digest();
//            StringBuffer sb = new StringBuffer();
//            for (int i=0; i<byteData.length; i++)
//                sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
//        
//            System.out.println("Thuc hien bam SHA: " + sb.toString());
//            txtBam.setText(sb.toString());
//               
//        }
//        catch(NoSuchAlgorithmException ex) {
//            Logger.getLogger(FormEncrypt.class.getName()).log(Level.SEVERE, null, ex);
//        }

        try{
            String user = txtmahoa.getText();
            String pass = txtvanban2.getText();
            String bam = "";
            bam = user + pass;
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(bam.getBytes());
            byte[] byteData = md.digest();
            StringBuffer sb = new StringBuffer();
            for(int i = 0; i < byteData.length; i++){
                sb.append(Integer.toString((byteData[i] & 0xff)+ 0x100, 16).substring(1));
            }
            System.out.println("Digest:: "+ sb.toString());
            txtBam.setText(sb.toString());
            StringBuffer hexString = new StringBuffer();
            for(int i = 0; i < byteData.length; i++){
                String hex = Integer.toHexString(0xff & byteData[i]);
                if(hex.length()==1){
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            System.out.println("Digest: "+hexString.toString());
            txtNoiChuoi.setText(bam.toString());
            BufferedWriter bw = null;
            String filename = "D:\\Bam.txt";
            bw = new BufferedWriter(new FileWriter(filename));
            bw.write(hexString.toString());
            bw.close();
            
       
           
       } catch (Exception ex){
           System.out.println("Loi bam "+ ex);
       }

    }//GEN-LAST:event_btnBamChuoiActionPerformed

    private void btnNoiChuoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoiChuoi2ActionPerformed
        // TODO add your handling code here:
        
        String noiChuoi = txtNoiChuoi.getText();
        String bam = txtBam.getText();
        String vanBan3 = txtvanban3.getText();

        String ketQua = noiChuoi + bam + vanBan3;
        txtNoiChuoi2.setText(ketQua);
        System.out.println("Noi chuoi N2: "+" "+ketQua);
        
        try {
            String content = txtvanban3.getText();
            File file = new File("D:\\M3.txt");

            // if file doesn't exist, create new file
            if (!file.exists()) {
                file.createNewFile();
            }

            // write content to file
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(content);
            bw.close();

            System.out.println("Da Luu File");
        } catch (IOException e) {
            e.printStackTrace();
        }     
        
        
    }//GEN-LAST:event_btnNoiChuoi2ActionPerformed

    private void btnMaHoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoa2ActionPerformed

        int k=Integer.valueOf(this.txtKhoa2.getText());
        String s=this.txtNoiChuoi2.getText();
        int n=s.length();
        int sd,sc;
        sd=k;
        sc=n/sd+1;
        char hr[][]=new char[sd][sc];
        int c,d;
        c=0;d=0;
        int sodu=n%sd;
        for(int i=0;i<n;i++)
        {
            hr[d][c]=s.charAt(i);
            d++;
            if(d==k){
                c++;d=0;
            }
        }
        String kq="";
        int sokytu=sc;
        for(int i=0;i<sd;i++){
            if(i>=sodu) sokytu=sc-1;
            for(int j=0;j<sokytu;j++)
                kq=kq+hr[i][j];
        }
        this.txtmahoa2.setText(kq);
 
        try {
            String content = txtmahoa2.getText();
            File file = new File("D:\\Encrypt.txt");

            // if file doesn't exist, create new file
            if (!file.exists()) {
                file.createNewFile();
            }

            // write content to file
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(content);
            bw.close();

            System.out.println("Da Luu File");
        } catch (IOException e) {
            e.printStackTrace();
        }     






    }//GEN-LAST:event_btnMaHoa2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEncrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEncrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEncrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEncrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEncrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBamChuoi;
    private javax.swing.JButton btnMaHoa;
    private javax.swing.JButton btnMaHoa2;
    private javax.swing.JButton btnNoiChuoi;
    private javax.swing.JButton btnNoiChuoi2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBam;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtKhoa2;
    private javax.swing.JTextField txtNoiChuoi;
    private javax.swing.JTextField txtNoiChuoi2;
    private javax.swing.JTextField txtmahoa;
    private javax.swing.JTextField txtmahoa2;
    private javax.swing.JTextField txtvanban;
    private javax.swing.JTextField txtvanban2;
    private javax.swing.JTextField txtvanban3;
    // End of variables declaration//GEN-END:variables
}
